### ISSUE TITLE
Provide Docker support for Wax

### ISSUE THREAD

**Issue by awoods** [minicomp/wax#84] opened 2020-07-28 00:10 UTC
This issue is to provide a means to both:
1. Run the demo and/or modified Wax project with Docker, and
1. Execute the derivative, pages, and search tasks within a Docker environment

**Comment by awoods** [comment] 2020-07-28 00:59
Potential resolution pull-requests:
   - https://github.com/minicomp/wax/pull/85
   - https://github.com/minicomp/wiki/pull/21

**Comment by awoods** [comment] 2020-07-28 12:40
In order to keep the documentation cleaner, it may be worth considering putting all of the Docker information in its own page.

**Comment by mnyrop** [comment] 2020-07-28 21:37
Hi @awoods, I had an idea to make the dual documentation easier. Let me know what you think.

I kept your commits + Dockerfile and added them to the [docker branch](https://github.com/minicomp/wax/tree/docker). Instead of running each command with `docker run` (e.g., `docker run --rm -v $PWD:/app --name wax-demo wax:1.1.0-snapshot "bundle exec rake wax:derivatives:simple YOUR_COLLECTION_NAME"`), how do you feel about:
 
1. building the image in advance, and 
2. having folks run all the commands (e.g., the tasks, jekyll serve, etc.) within an interactive bash shell from the image? 

That way, each task doesn't need to have 2 docs (native vs. docker) because, once you're in the shell, almost everything* should be the same.

Steps to reproduce/test:

- Build the base image: `docker build -t ubuntu/wax .`
- Start a container + open the shell: `docker run -it -p 4000:4000 ubuntu/wax bash`
- Run any task to test, e.g., `bundle exec rake wax:pages qatar` from within the container
- Run the jekyll server within the container + view demo in host browser: `bundle exec jekyll serve --host 0.0.0.0`

(\* By almost everything, I mean everything except `jekyll serve`, which unfortunately needs `--host 0.0.0.0` within Docker.)

**Comment by awoods** [comment] 2020-07-29 03:35
@mnyrop : sounds like a great idea... and the updated Docker and instructions above work as advertised.

**Comment by mnyrop** [comment] 2020-07-29 15:27
@awoods good point. would you be okay with me:

- using the method above in the main docs, and 
- asking you to contribute a Wax "recipe" for using Docker with a mounted volume? I'd love to add your workaround to the (currently non-existent) recipes section of the wiki! (So far I only tested this option with [docker-compose](https://matthiaslischka.at/2018/12/22/jekyll-docker-compose/), which may or may not make sense.)

Also before I merge into master: are you okay with being the maintainer of the Dockerfile, per [line 3](https://github.com/minicomp/wax/blob/docker/Dockerfile#L3)? 

Thanks again for your contributions on this!

**Comment by awoods** [comment] 2020-07-29 16:51
@mnyrop : it all sounds good.
Regarding maintenance of Dockerfile, I am not expert, but am happy to help as I can.

**Comment by mnyrop** [comment] 2020-07-30 01:24
Merged into master via #87

**Closed by mnyrop** 2020-07-30 01:24 UTC
